### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by nolanryno** [anon-real/ErgoAuctionHouse#27] opened 2021-08-12 01:31 UTC
Users should be able to search using keywords or search by an artist name or using hashtags. If possible, we can start using categories to group as we find out what types of NFTs are being utilized. Overall there is no way to search at all for what I may be looking for.

**Comment by sepehr2github** [comment] 2021-08-29 08:18
Working on it !

**Comment by anon-real** [comment] 2021-09-28 11:45
duplicate of #31

**Closed by anon-real** 2021-09-28 11:45 UTC
